dtbo-y += i2c1.dtbo \
	i2c2.dtbo \
	i2s.dtbo \
	os08a10.dtbo \
	pwm_c-beeper.dtbo \
	pwm_cd-c.dtbo \
	pwm_cd.dtbo \
	pwm_ef.dtbo \
	pwm_ef-f.dtbo \
	sdio.dtbo \
	spi0.dtbo \
	spi0_flash.dtbo \
	uart1_cts_rts.dtbo \
	uart1.dtbo \
	uart2.dtbo \
	wifi_bt_rtl8822cs.dtbo \
	waveshare_tft35c_lcd.dtbo \
	waveshare_tft24_lcd.dtbo \
	hifi_pcm5122.dtbo \
	i2smic.dtbo \
	pdmmic.dtbo \
	otg-device.dtbo \
	otg-host.dtbo

targets += $(dtbo-y)
always  := $(dtbo-y)
